### PR TITLE
replaceAll chain's gone for good

### PR DESCRIPTION
**Pull request by NoobJsPerson**
Replaced the replaceAll chain by the interpolate function and added FPS to the mod message (it was messing b4) but the formatting got screwed ._.

### CODE REVIEW

**Comment by Mango0x45** [comment]
Could you use tabs as opposed to cringe 2 space indents?

**Comment by NoobJsPerson** [comment]
My text editor won't let me

**Comment by NoobJsPerson** [comment]
Every single time i save its freaking spaces

**Comment by Mango0x45** [comment]
`unexpand --first-only -t 2 main.js > main_with_tabs.js`

**Comment by NoobJsPerson** [comment]
Ohh thx wait

**Comment by NoobJsPerson** [comment]
Should i close and re-request now?

**Pull request merged**
